# Generated by Django 4.2.6 on 2023-10-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('pub_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Accessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_checked_out', models.TimeField(auto_now_add=True)),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms_app.books')),
            ],
        ),
    ]
