# Generated by Django 4.2.6 on 2023-10-31 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accessor',
            table='Accessor',
        ),
        migrations.AlterModelTable(
            name='books',
            table='Books',
        ),
    ]
