# Generated by Django 4.2.6 on 2023-11-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0002_alter_accessor_table_alter_books_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accessor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='books',
            table=None,
        ),
    ]
