# Generated by Django 4.2.6 on 2023-11-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0003_alter_accessor_table_alter_books_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessor',
            name='mail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
