# Generated by Django 4.2.6 on 2023-11-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_app', '0004_accessor_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessor',
            name='book_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accessor',
            name='date_checked_out',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
